import Head from 'next/head'
import Productcomponent from '../components/Product'
import { useEffect , useContext} from 'react'
import Product from '../models/Product'
import mongoose from 'mongoose'
export default function Home({products}) {
  // if(typeof window!=='undefined'){
  //   let homebody = window.document.body.style
  // homebody.backgroundImage = "url('homebg.jpg')";
  // homebody.backgroundColor = "black";
  // homebody.backgroundSize = "cover";
  // }
  return (
    <>
    <style jsx>
          {`
            
          `}
          
        </style>
    <div className='home p-4 box-border'>
      <Head>
        <title>{process.env.WEBSITE_NAME[0].toUpperCase()+process.env.WEBSITE_NAME.slice(1)  }</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        
      </Head>
    <Productcomponent className="bg-red-300" count={'5'} products={products} />
    </div>
    </>
  )
}
export async function getServerSideProps(context){
  if (!mongoose.connections[0].readyState){
    await mongoose.connect(process.env.MONGOURI)
  }
  let products = await Product.find();
  return {
    props:{
      products:JSON.parse(JSON.stringify(products))
    }
  }
}